import { DrugCandidate } from "@/app/types";

export const mockDrugCandidates: DrugCandidate[] = [
  {
    id: "dc-001",
    name: "Neurodexin",
    status: "In Development",
    description: "Neurodexin is a treatment candidate for Cardiology.",
    mechanismOfAction:
      "Neurodexin works by modulating a specific biological target.",
    sideEffects: ["Headache", "Fever", "Dry mouth"],
    clinicalTrials: ["NCT75168426", "NCT64055379"],
    approvalDate: undefined,
    manufacturer: "Global Biologics",
    therapeuticArea: "Endocrinology",
    administrationRoute: "IV",
    dosageForm: "Inhaler",
  },
  {
    id: "dc-002",
    name: "Cardiostat",
    status: "Approved",
    description: "Cardiostat is a treatment candidate for Dermatology.",
    mechanismOfAction:
      "Cardiostat works by modulating a specific biological target.",
    sideEffects: ["Fever", "Dizziness", "Nausea", "Fatigue"],
    clinicalTrials: ["NCT22926374", "NCT43986699"],
    approvalDate: "2023-02-04",
    manufacturer: "NeuroPharma Ltd.",
    therapeuticArea: "Oncology",
    administrationRoute: "Subcutaneous",
    dosageForm: "Tablet",
  },
  {
    id: "dc-003",
    name: "Immunocure",
    status: "Rejected",
    description: "Immunocure is a treatment candidate for Dermatology.",
    mechanismOfAction:
      "Immunocure works by modulating a specific biological target.",
    sideEffects: ["Muscle pain", "Fever", "Dizziness", "Fatigue"],
    clinicalTrials: ["NCT60689839"],
    approvalDate: undefined,
    manufacturer: "Meditech Inc.",
    therapeuticArea: "Gastroenterology",
    administrationRoute: "Oral",
    dosageForm: "Tablet",
  },
  {
    id: "dc-004",
    name: "Glucostatin-X",
    status: "Rejected",
    description: "Glucostatin-X is a treatment candidate for Immunology.",
    mechanismOfAction:
      "Glucostatin-X works by modulating a specific biological target.",
    sideEffects: ["Fever", "Nausea"],
    clinicalTrials: ["NCT64892031", "NCT36122716"],
    approvalDate: undefined,
    manufacturer: "GenPharm Inc.",
    therapeuticArea: "Gastroenterology",
    administrationRoute: "IV",
    dosageForm: "Capsule",
  },
  {
    id: "dc-005",
    name: "Pulmovir",
    status: "Approved",
    description: "Pulmovir is a treatment candidate for Gastroenterology.",
    mechanismOfAction:
      "Pulmovir works by modulating a specific biological target.",
    sideEffects: ["Dry mouth", "Fatigue", "Dizziness", "Fever"],
    clinicalTrials: ["NCT84649041"],
    approvalDate: "2023-10-09",
    manufacturer: "NeuroPharma Ltd.",
    therapeuticArea: "Neurology",
    administrationRoute: "Subcutaneous",
    dosageForm: "Cream",
  },
  {
    id: "dc-006",
    name: "Oncomab",
    status: "Approved",
    description: "Oncomab is a treatment candidate for Cardiology.",
    mechanismOfAction:
      "Oncomab works by modulating a specific biological target.",
    sideEffects: ["Dry mouth", "Muscle pain"],
    clinicalTrials: ["NCT25733226"],
    approvalDate: "2024-07-17",
    manufacturer: "Global Biologics",
    therapeuticArea: "Oncology",
    administrationRoute: "Inhalation",
    dosageForm: "Tablet",
  },
  {
    id: "dc-007",
    name: "Hepacure",
    status: "In Development",
    description: "Hepacure is a treatment candidate for Endocrinology.",
    mechanismOfAction:
      "Hepacure works by modulating a specific biological target.",
    sideEffects: ["Nausea", "Headache", "Muscle pain", "Fever"],
    clinicalTrials: ["NCT91835765"],
    approvalDate: undefined,
    manufacturer: "Meditech Inc.",
    therapeuticArea: "Gastroenterology",
    administrationRoute: "IV",
    dosageForm: "Inhaler",
  },
  {
    id: "dc-008",
    name: "Dermaclear",
    status: "Rejected",
    description: "Dermaclear is a treatment candidate for Dermatology.",
    mechanismOfAction:
      "Dermaclear works by modulating a specific biological target.",
    sideEffects: ["Nausea", "Dizziness", "Fatigue"],
    clinicalTrials: ["NCT31834180"],
    approvalDate: undefined,
    manufacturer: "OncoLab",
    therapeuticArea: "Gastroenterology",
    administrationRoute: "Topical",
    dosageForm: "Inhaler",
  },
  {
    id: "dc-009",
    name: "Nephrosafe",
    status: "Rejected",
    description: "Nephrosafe is a treatment candidate for Immunology.",
    mechanismOfAction:
      "Nephrosafe works by modulating a specific biological target.",
    sideEffects: ["Muscle pain", "Dry mouth", "Fever", "Nausea"],
    clinicalTrials: ["NCT82220780"],
    approvalDate: undefined,
    manufacturer: "GenPharm Inc.",
    therapeuticArea: "Oncology",
    administrationRoute: "Topical",
    dosageForm: "Inhaler",
  },
  {
    id: "dc-010",
    name: "Oculonix",
    status: "In Development",
    description: "Oculonix is a treatment candidate for Dermatology.",
    mechanismOfAction:
      "Oculonix works by modulating a specific biological target.",
    sideEffects: ["Dizziness", "Fever", "Nausea", "Dry mouth"],
    clinicalTrials: ["NCT15521699"],
    approvalDate: undefined,
    manufacturer: "OncoLab",
    therapeuticArea: "Oncology",
    administrationRoute: "Inhalation",
    dosageForm: "Cream",
  },
  {
    id: "dc-011",
    name: "Pancrelif",
    status: "In Development",
    description: "Pancrelif is a treatment candidate for Cardiology.",
    mechanismOfAction:
      "Pancrelif works by modulating a specific biological target.",
    sideEffects: ["Muscle pain", "Nausea", "Fatigue"],
    clinicalTrials: ["NCT12588145"],
    approvalDate: undefined,
    manufacturer: "OncoLab",
    therapeuticArea: "Gastroenterology",
    administrationRoute: "Subcutaneous",
    dosageForm: "Injection",
  },
  {
    id: "dc-012",
    name: "Arthricalm",
    status: "Approved",
    description: "Arthricalm is a treatment candidate for Immunology.",
    mechanismOfAction:
      "Arthricalm works by modulating a specific biological target.",
    sideEffects: ["Headache", "Fever"],
    clinicalTrials: ["NCT89064615", "NCT24984221"],
    approvalDate: "2022-11-16",
    manufacturer: "PharmaWorld",
    therapeuticArea: "Endocrinology",
    administrationRoute: "Topical",
    dosageForm: "Injection",
  },
  {
    id: "dc-013",
    name: "Lungair",
    status: "In Development",
    description: "Lungair is a treatment candidate for Endocrinology.",
    mechanismOfAction:
      "Lungair works by modulating a specific biological target.",
    sideEffects: ["Dry mouth", "Nausea", "Fever"],
    clinicalTrials: ["NCT28186256"],
    approvalDate: undefined,
    manufacturer: "NeuroPharma Ltd.",
    therapeuticArea: "Endocrinology",
    administrationRoute: "IV",
    dosageForm: "Capsule",
  },
  {
    id: "dc-014",
    name: "Zentraphin",
    status: "In Development",
    description: "Zentraphin is a treatment candidate for Pulmonology.",
    mechanismOfAction:
      "Zentraphin works by modulating a specific biological target.",
    sideEffects: ["Headache", "Fever"],
    clinicalTrials: ["NCT55629202", "NCT76423432"],
    approvalDate: undefined,
    manufacturer: "OncoLab",
    therapeuticArea: "Gastroenterology",
    administrationRoute: "Oral",
    dosageForm: "Tablet",
  },
  {
    id: "dc-015",
    name: "Myostem",
    status: "Approved",
    description: "Myostem is a treatment candidate for Dermatology.",
    mechanismOfAction:
      "Myostem works by modulating a specific biological target.",
    sideEffects: ["Nausea", "Headache", "Fever"],
    clinicalTrials: ["NCT89477474", "NCT38442857"],
    approvalDate: "2023-03-27",
    manufacturer: "OncoLab",
    therapeuticArea: "Gastroenterology",
    administrationRoute: "Topical",
    dosageForm: "Capsule",
  },
  {
    id: "dc-016",
    name: "Thymogen",
    status: "Approved",
    description: "Thymogen is a treatment candidate for Endocrinology.",
    mechanismOfAction:
      "Thymogen works by modulating a specific biological target.",
    sideEffects: ["Nausea", "Fever"],
    clinicalTrials: ["NCT12815475"],
    approvalDate: "2023-09-23",
    manufacturer: "BioNova",
    therapeuticArea: "Gastroenterology",
    administrationRoute: "Inhalation",
    dosageForm: "Cream",
  },
  {
    id: "dc-017",
    name: "Biosera",
    status: "In Development",
    description: "Biosera is a treatment candidate for Dermatology.",
    mechanismOfAction:
      "Biosera works by modulating a specific biological target.",
    sideEffects: ["Fatigue", "Nausea"],
    clinicalTrials: ["NCT56242788", "NCT67905177"],
    approvalDate: undefined,
    manufacturer: "BioNova",
    therapeuticArea: "Oncology",
    administrationRoute: "Inhalation",
    dosageForm: "Inhaler",
  },
  {
    id: "dc-018",
    name: "Metaboquest",
    status: "Approved",
    description: "Metaboquest is a treatment candidate for Dermatology.",
    mechanismOfAction:
      "Metaboquest works by modulating a specific biological target.",
    sideEffects: ["Nausea", "Fever", "Dry mouth", "Muscle pain"],
    clinicalTrials: ["NCT89320407"],
    approvalDate: "2024-04-06",
    manufacturer: "NeuroPharma Ltd.",
    therapeuticArea: "Cardiology",
    administrationRoute: "Subcutaneous",
    dosageForm: "Injection",
  },
  {
    id: "dc-019",
    name: "Cognitrol",
    status: "Approved",
    description: "Cognitrol is a treatment candidate for Pulmonology.",
    mechanismOfAction:
      "Cognitrol works by modulating a specific biological target.",
    sideEffects: ["Dry mouth", "Muscle pain", "Dizziness", "Nausea"],
    clinicalTrials: ["NCT34112983", "NCT90529895"],
    approvalDate: "2024-04-29",
    manufacturer: "PharmaWorld",
    therapeuticArea: "Dermatology",
    administrationRoute: "Oral",
    dosageForm: "Inhaler",
  },
  {
    id: "dc-020",
    name: "Virostatin",
    status: "Rejected",
    description: "Virostatin is a treatment candidate for Oncology.",
    mechanismOfAction:
      "Virostatin works by modulating a specific biological target.",
    sideEffects: ["Muscle pain", "Fatigue"],
    clinicalTrials: ["NCT11660334"],
    approvalDate: undefined,
    manufacturer: "BioNova",
    therapeuticArea: "Neurology",
    administrationRoute: "Topical",
    dosageForm: "Cream",
  },
];
